apiVersion: v1
kind: ConfigMap
metadata:
  name: knot
  namespace: default
data:
  KNOT_TYPE: github
  KNOT_URI: owner/garreeoke/repository/k8_setup/branch/master
  KNOT_AUTH: cluster
  KNOT_ACTION: create
  KNOT_WHITELIST: "acme-air"
  #GITHUB_USER: ""
  #GITHUB_TOKEN: ""